"""Generated views of the bench. Never hand-maintained.

The vault's standing rule -- "never hand-maintain a catalog; if you find
yourself writing a list of notes, write a Base instead" -- applies to a repo
just as well. `variants/README.md` and `variants/CHANGELOG.md` are both
regenerated from the variant files and the lock, so the answer to "what have we
tried, and what is live" is never one edit behind the truth.

Regenerated automatically by `bench promote`, and on demand by `bench registry`.
"""
from __future__ import annotations

from pathlib import Path

from bench import lock, scorecard as sc_mod
from bench import variant as bench_variant
from bench import fingerprint

REGISTRY_PATH = bench_variant.VARIANTS_DIR / "README.md"
CHANGELOG_PATH = bench_variant.VARIANTS_DIR / "CHANGELOG.md"

_STATUS_ORDER = {"promoted": 0, "testing": 1, "draft": 2,
                 "rejected": 3, "superseded": 4}


def _verdict_cell(name: str) -> str:
    cards = sc_mod.for_variant(name)
    if not cards:
        return "—"
    c = cards[0]
    d = c.delta()
    bits = [f"{label} {d[k]:+.2f}"
            for k, label in (("sharpe", "Sharpe"), ("ret_per_maxdd", "ret/DD"))
            if k in d]
    tag = c.tier if c.is_evidence else f"{c.tier}*"
    return f"{tag}: " + (", ".join(bits) if bits else "ran, no comparable metrics")


def registry_markdown() -> str:
    variants = bench_variant.all_variants()
    rows = sorted(variants.values(),
                  key=lambda v: (_STATUS_ORDER.get(v.status, 9), v.name))
    L = ["# Variants — every paragraph, and what became of it",
         "",
         "GENERATED by `bench registry`. Do not edit by hand.",
         "",
         "`frozen` is the master document: what the live paper bot actually runs.",
         "`plain` is the control arm: the engine defaults, every flag off.",
         "A `*` on a tier means the scorecard is stamped **not evidence** "
         "(smoke runs).",
         "",
         "| variant | status | base | question | knobs | newest scorecard |",
         "|---|---|---|---|---|---|"]
    for v in rows:
        q = (v.question or v.note.strip().split("\n")[0] or "—")
        q = q.replace("|", "\\|")
        if len(q) > 90:
            q = q[:87] + "…"
        knobs = ", ".join(f"`{k}`" for k in list(v.knobs)[:4])
        if len(v.knobs) > 4:
            knobs += f" +{len(v.knobs)-4}"
        # Link relative to variants/, so an archived variant points at
        # `_archive/x.toml` rather than at a sibling that does not exist.
        href = ""
        if v.path:
            try:
                href = str(Path(v.path).resolve().relative_to(
                    bench_variant.VARIANTS_DIR.resolve()))
            except ValueError:
                href = Path(v.path).name
        L.append(f"| [`{v.name}`]({href}) "
                 f"| {v.status} | {v.base or '—'} | {q} | {knobs or '—'} "
                 f"| {_verdict_cell(v.name)} |")

    L += ["", "## How a paragraph becomes part of the essay", "",
          "```",
          "bench new <name> --question \"what must this prove?\"",
          "bench run <name> --tier smoke      # seconds — does it do anything?",
          "bench run <name>                   # full tier — the verdict",
          "bench replay <name> --since ...    # required if it touches liquidity",
          "bench promote <name> --dry-run     # what would change, and what blocks it",
          "bench promote <name> --verdict \"...\"",
          "```", "",
          "`bench promote` is the ONLY sanctioned way to change "
          "`variants/frozen.toml`. A hand-edit fails "
          "`bench doctor`, which compares it to "
          "`frozen.lock.json`, before the pre-push hook lets it out.", ""]
    return "\n".join(L)


def regenerate() -> list[str]:
    written = []
    REGISTRY_PATH.write_text(registry_markdown(), encoding="utf-8")
    written.append(fingerprint.rel(REGISTRY_PATH))
    try:
        CHANGELOG_PATH.write_text(lock.changelog_markdown(), encoding="utf-8")
        written.append(fingerprint.rel(CHANGELOG_PATH))
    except FileNotFoundError:
        pass
    return written
